theme: jekyll-theme-minimal
title: Jason Ball
description: Computer Science/Software Engineering student at VCU. Intern at NOAA's Florida Keys National Marine Sanctuary. he/him/his
logo: https://github.com/jason-ball.png
twitter: https://twitter.com/JasonBall_dev
